#!/usr/bin/env python

#    This file is part of FileZaar.
#    FileZaar is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#   FileZaar is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with FileZaar.  If not, see <http://www.gnu.org/licenses/>.

This file has instructions on how to download and install filezaar on your 
computer, please notice that this is a realy early version, meant only for 
developers. You are at your own risk!!


Required OS: Linux, (it only has been tested on Ubuntu 9.10 ad above, but it 
                    should work also on any linux with the libraries mentioned
                    below), it also requires a kernel with INOTIFY support. 
                    if you don't know what I'm talking about, you already 
                    have it :).

Required libraries: python-inotify>=0.8.6, python-notify, bzrlib >= version 1.13 

Notes: 
- If you are using Ubuntu 8.10 you can install bzrlib using easy_install,
    because Ubuntu 8.10 has an old and buggy version on its repositories),
    otherwise stick to the apt version.


Download/Install:
================

- CheckOut the source code to a directory of your preference.

$ mkdir filezaarsource
$ cd /home/user/filezaarsource
$ bzr branch lp:filezaar


Configuring it:
==============
In order to run filezaar you need a repostitory to store all your files.
you can create it anywhere you want as long as it is accesible to all your
filezaar installations.

The easiest way to test it is to create a repository on the same box, you 
can use the script setup_bazaar.sh for that purpose


$ sh setup.sh REMOTE_REPOSITORY_URI LOCAL_FILE_PATH

REMOTE_REPOSITORY_URI: URI of your repository i.e.:
    file:///tmp/filezaar_repo

LOCAL_FILE_PATH: Desired filepath for your local files i.e.:
    /tmp/filezaar_local


This script will create both the repository and the local file directories.

It will also create a ~/filezaarrc file with the configuration
(check filezaarrc.dist file for an example)


Running FileZaar:
================

Note: Before running filezaar for the first time be sure to have the 

1) Export the PYTHONPATH environment variable

$ export PYTHONPATH=/home/user/filezaarsource:{$PYTHONPATH}

2) From within the directory where the source code has been installed simply run:

$ python filezaardaemon.py

To test if it is working just copy or create a file inside the 
"local_files_dir" you configured in your .filezaarrc file and it
will be automatically synchronized with the remote repository

If you want to receive notifications run also:

$ python filezaar-client.py
